production: &production
  facebook:
    key: 568124317022786
    secret: f409ba7d1c87c54eb03f6bc0aaa6555c
  google:
    key: 1075676587314-dear5aabgf35u251jjl13msvkci8c5gi.apps.googleusercontent.com
    secret: OiaFAYf0fIjf0VnFrelGRtq2
development: &development
  <<: *production
  facebook:
    key: 568124317022786
    secret: f409ba7d1c87c54eb03f6bc0aaa6555c
  google:
    key: 1075676587314-dear5aabgf35u251jjl13msvkci8c5gi.apps.googleusercontent.com
    secret: OiaFAYf0fIjf0VnFrelGRtq2
test:
  <<: *development
